version: '3.8'
services:
  db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: 'filmdb'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d filmdb -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
#    command: ./main
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres


networks:
  postgres:
    driver: bridge