Server:
  AppVersion: "1.0.0"
  Host: "0.0.0.0"
  Port: "8080"
  Timeout: 60s

Postgres:
  host: "postgres"
  port: "5432"
  user: "root"
  password: "root"
  DBName: "filmdb"
  sslMode: "disable"
  pgDriver: "pgx"